"""
problem3.py
====

Author:  

Part 1: 
The book 'War an Peace' can be accessed at 
  http://www.gutenberg.org/files/2600/2600-0.txt 
on the project Gutenberg website. 

Write a program that determines the number of times that each of the 
words in the title appear in the text of the file. For 'War an Peace', the
program should count the occurences of 'war', 'and' and 'peace'. 

Make sure that your program counts all occurences including the ones that may 
be in uppercase or that start with uppercase letter. 
Your program should also count occurences of the title strings when they are 
a part of a bigger word, for example 'wardrobe'.

Part 2:
Go to project Gutenberg website http://www.gutenberg.org/ and find another book. 
Make sure to get the url of the text file containing the book (almost every single
book on the website is available in the text format). 
Repeat part 1 with the title of the book that you picked (each word of the 
title should be counted). 

     

==============
Here is the output that should be generated by your program for 'War and Peace':

'war' appears  1301 times
'and' appears  27090 times
'peace' appears  139 times

==============

__COMMENT YOUR SOURCE CODE__ by 

* briefly describing parts of your program 
* including your name at the top of your
  file (above these instructions)
"""

